name:                site

version:             0.1.0.0

synopsis:            A simple blog with hakyll
description:         This is a blog with hakyll in github being deployed by circleci
homepage:            https://github.com/lokesh1197/lokesh1197.github.io#readme
license:             BSD3
license-file:        LICENSE
author:              Lokesh Mohanty
maintainer:          lokesh1197@gmail.com
copyright:           Copyright (c) 2020 Lokesh Mohanty
category:            Web
build-type:          Simple
extra-source-files:  README.md

dependencies:
  - base == 4.11.*
  - hakyll == 4.12.*

executables:
  site:
    main: site.hs

ghc-options: -threaded
