name: Haskell CI

on:
  push:
    branches: [ hakyll ]
  pull_request:
    branches: [ hakyll ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        stack-version: '2.2'

    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.DEPLOY_PRIVATE_KEY }}"
                    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('package.yaml') }}

    - name: Resolve/Update dependencies
      run: |
        stack setup
        stack build --dependencies-only
        
    - name: Build Site
      run: stack build --pedantic
      
    - name: Generate Static Site
      run: stack exec site build
      
    - name: Publish GitHub Pages 
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        stack exec site build
        cd _site
        git init
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        git remote add origin git@github.com:lokesh1197/lokesh1197.github.io.git
        git config --global user.email "actions@github"
        git config --global user.name "Github Actions"
        git add -A 
        git commit -m "publish  $GITHUB_SHA on (`date '+%F %T %Z'`) [ci skip]"
        git push -u origin master
