name: Haskell CI

on:
  push:
    branches: [ hakyll ]
  pull_request:
    branches: [ hakyll ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.2'
        stack-version: '2.2'
    - name: Install dependencies
      run: |
        stack build
    - name: Run tests
      run: |
        stack exec site build
        git checkout master
        cp -a _site/ .
        git add -A 
        git commit -m "test"
        git push origin master
